name: "Release"

on:
  push:
    branches:
      - main

jobs:
  tag:
    name: Auto Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for reading package.json)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Read version from package.json
        id: get_version_node
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Read version from pyproject.toml
        if: ${{ steps.get_version_node.outputs.version == '' }}
        id: get_version_py
        run: |
          VERSION=$(grep -Po '(?<=^version = ")[^"]*' pyproject.toml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.get_version_node.outputs.version || steps.get_version_py.outputs.version }}
          tag_prefix: ""  # Optional: remove if you want "v1.0.0" style tags
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Optional: remove if you want to use GITHUB_TOKEN
